// Real Chromium acceptance checks. Owns and closes its private browser only.
import assert from 'node:assert/strict';
import { writeFile, mkdir, readFile } from 'node:fs/promises';
import { launchChrome, waitFor } from './cdp.mjs';
import { createServer } from 'node:http';
import { fileURLToPath } from 'node:url';
import { gzipSync } from 'node:zlib';
import { createHash } from 'node:crypto';
import { CONFIG } from '../src/config.js';
import { World } from '../src/world.js';
import { Stats } from '../src/stats.js';
import { replayExperiment, validateExperiment } from './replay-lab.mjs';
import { makePlan, compareOutcome } from '../src/lab.js';
const origin=process.env.GENESIS_ORIGIN||'http://127.0.0.1:5173';
await mkdir(new URL('../evidence/',import.meta.url),{recursive:true});
Object.assign(CONFIG,{seed:'browser-acceptance',width:600,height:400,startPopulation:20,maxPopulation:100,startFood:60,maxFood:150,maxCarrion:50,foodRate:2,bloomCount:3,statsEvery:4});
const w=new World(),stats=new Stats(16);stats.sample(w);for(let i=0;i<40;i++){w.step(1);if(w.tick%4===0)stats.sample(w);}
const fixture={schemaVersion:2,provenance:{config:structuredClone(CONFIG)},state:w.toState(),history:stats.toJSON()};
const results=[],errors=[];let browser, fallbackServer;
async function check(name,fn){try{const detail=await fn();results.push({name,ok:true,detail});console.log('PASS',name);}catch(e){results.push({name,ok:false,error:e.stack});console.error('FAIL',name,e.message);}}
try {
 browser=await launchChrome({url:origin+'/?record=1&tour=0',width:1440,height:1000,extraArgs:['--enable-unsafe-swiftshader']});const c=browser.cdp;
 c.on('Runtime.exceptionThrown',e=>errors.push(e.exceptionDetails.exception?.description||e.exceptionDetails.text));
 await waitFor(c,'!!window.__GENESIS');await c.evaluate('window.__GENESIS.ready');
 await check('recording does not autonomously step',async()=>{const a=await c.evaluate('__GENESIS.sim.view?.tick');await new Promise(r=>setTimeout(r,150));const b=await c.evaluate('__GENESIS.sim.view?.tick');assert.equal(a,b);return{tick:b};});
 await check('valid exact checkpoint, configuration, and full history load',async()=>{await c.evaluate(`__GENESIS.load(${JSON.stringify(fixture)})`);const out=await c.evaluate('({tick:__GENESIS.sim.view.tick,history:__GENESIS.sim.historyTicks,foodRate:__GENESIS.sim.config.foodRate})');assert.equal(out.tick,40);assert.equal(out.history[0],0);assert.equal(out.foodRate,2);return out;});
 await check('loaded thresholds reach renderer uniforms and inspector labels',async()=>{const changed=structuredClone(fixture);for(const cfg of [changed.provenance.config,changed.state.config]){cfg.carnivoreThreshold=-1;cfg.scavengerLabel=.2;cfg.maxAge=777;}await c.evaluate(`__GENESIS.load(${JSON.stringify(changed)})`);await c.evaluate('(()=>{const id=__GENESIS.sim.view.creatureAt(0).id;__GENESIS.state.selectedId=id;__GENESIS.sim.send({type:"select",id});})()');await waitFor(c,'__GENESIS.sim.inspect?.alive');const out=await c.evaluate(`(()=>{for(let i=0;i<4;i++)__GENESIS.render();const r=__GENESIS.renderer;return{uniform:r.gl.getUniform(r.creatureProg,r.cu.carn),age:r.config.maxAge,effective:__GENESIS.CONFIG.carnivoreThreshold,inspector:document.getElementById('specimenStats').textContent};})()`);assert.equal(out.uniform,-1);assert.equal(out.age,777);assert.equal(out.effective,-1);assert.match(out.inspector,/carnivore/);await c.evaluate(`__GENESIS.load(${JSON.stringify(fixture)})`);return out;});
 await check('verified gzip checkpoint decodes and rejects altered checksum',async()=>{const bytes=gzipSync(JSON.stringify(fixture)),url='data:application/octet-stream;base64,'+bytes.toString('base64'),sha256=createHash('sha256').update(bytes).digest('hex');const out=await c.evaluate(`__GENESIS.fetchCheckpoint(${JSON.stringify({url,sha256})}).then(c=>({tick:c.state.tick,version:c.state.v}))`);assert.deepEqual(out,{tick:40,version:4});const bad=await c.evaluate(`__GENESIS.fetchCheckpoint(${JSON.stringify({url,sha256:'0'.repeat(64)})}).then(()=>false,e=>e.message)`);assert.match(bad,/checksum mismatch/);return{...out,corrupt:bad};});
 await check('missing checkpoint reports actionable download failure',async()=>{const out=await c.evaluate(`__GENESIS.fetchCheckpoint({url:'./checkpoints/does-not-exist.json'}).then(()=>false,e=>e.message)`);assert.match(out,/404/);return out;});
 await check('setCamera changes the real camera',async()=>{const out=await c.evaluate('(()=>{__GENESIS.setCamera({cx:123,cy:234,zoom:.9});return{cx:__GENESIS.renderer.camera.cx,cy:__GENESIS.renderer.camera.cy,zoom:__GENESIS.renderer.camera.zoom};})()');assert.deepEqual(out,{cx:123,cy:234,zoom:.9});return out;});
 await check('step acknowledgement contains exact snapshot tick',async()=>{const r=await c.evaluate('__GENESIS.step(3,{stats:false})');assert.equal(r.tick,43);assert.equal(await c.evaluate('__GENESIS.sim.view.tick'),43);return r;});
 await check('checkpoint replay preserves exact state in browser runtime',async()=>{const r=await c.evaluate(`(async()=>{await __GENESIS.load(${JSON.stringify(fixture)});await __GENESIS.step(11,{stats:false});const a=await __GENESIS.checkpoint();await __GENESIS.load(${JSON.stringify(fixture)});await __GENESIS.step(11,{stats:false});const b=await __GENESIS.checkpoint();return JSON.stringify(a.state)===JSON.stringify(b.state);})()`);assert.equal(r,true);return r;});
 await check('Muller origin is retained and clade band selection works',async()=>{await c.evaluate('for(let i=0;i<32;i++)__GENESIS.render()');const r=await c.evaluate(`(()=>{const cv=document.getElementById('mullerRibbon');const hit=cv._mullerPick?.(cv.clientWidth/2,cv.clientHeight/2);cv.dispatchEvent(new MouseEvent('click',{clientX:cv.getBoundingClientRect().left+cv.clientWidth/2,clientY:cv.getBoundingClientRect().top+cv.clientHeight/2,bubbles:true}));return {hit,selected:__GENESIS.state.selectedSpecies,highlight:[...(__GENESIS.state.highlightSpecies||[])]};})()`);assert.notEqual(r.hit,null);assert.equal(r.selected,r.hit);assert.ok(r.highlight.includes(r.hit));return r;});
 await check('guided observation can be restarted and taken over',async()=>{const r=await c.evaluate(`(()=>{document.getElementById('restartTour').click();const shown=!document.getElementById('tour').hidden;document.getElementById('tourNext').click();const title=document.getElementById('tourTitle').textContent;document.getElementById('takeControl').click();return {shown,title,hidden:document.getElementById('tour').hidden};})()`);assert.ok(r.shown&&r.hidden);assert.equal(r.title,'Read the three colors.');return r;});
 await check('Ecology Lab requires and locks a prediction',async()=>{const r=await c.evaluate(`(()=>{const p=document.getElementById('labPrediction');p.value='';return {valid:document.getElementById('labForm').checkValidity(),defaultTicks:document.getElementById('labTicks').value};})()`);assert.equal(r.valid,false);assert.equal(r.defaultTicks,'1800');return r;});
 await check('Ecology Lab completes two isolated branches at exact target',async()=>{await c.evaluate(`__GENESIS.load(${JSON.stringify(fixture)})`);await c.evaluate(`(()=>{document.getElementById('labPrediction').value='15';document.getElementById('labTicks').value='13';document.getElementById('labForm').requestSubmit();})()`);const locked=await c.evaluate('document.getElementById("labPrediction").disabled');assert.equal(locked,true);await waitFor(c,'__GENESIS.lastExperiment?.plan.ticks===13');const out=await c.evaluate(`(()=>{const e=__GENESIS.lastExperiment;return {plan:e.plan,result:e.result,ticks:[e.branches.control.metrics.tick,e.branches.intervention.metrics.tick],commands:e.commands,mainTick:__GENESIS.sim.view.tick};})()`);assert.deepEqual(out.ticks,[53,53]);assert.equal(out.mainTick,40);assert.equal(out.plan.prediction,15);assert.deepEqual(out.plan.patch,{foodRate:1});assert.equal(out.commands.filter(x=>x.command==='load-checkpoint').length,2);return out;});
 await check('experiment export includes checkpoint, config, prediction, and trace',async()=>{await c.evaluate(`(()=>{window._exportURL=URL.createObjectURL;window._anchorClick=HTMLAnchorElement.prototype.click;URL.createObjectURL=b=>{window._exportBlob=b;return window._exportURL(b);};HTMLAnchorElement.prototype.click=function(){};document.getElementById('labExport').click();})()`);await waitFor(c,'!!window._exportBlob');const out=await c.evaluate(`(async()=>{const e=JSON.parse(await window._exportBlob.text());URL.createObjectURL=window._exportURL;HTMLAnchorElement.prototype.click=window._anchorClick;window._exportExperiment=e;return{hash:e.checkpointSHA256,prediction:e.plan.prediction,config:e.plan.config.foodRate,tick:e.checkpoint.state.tick,commands:e.commands.length};})()`);assert.equal(out.hash.length,64);assert.equal(out.prediction,15);assert.equal(out.config,2);assert.equal(out.tick,40);assert.equal(out.commands,5);return out;});
 await check('exported browser experiment replays with verified checksum and outcomes',async()=>{const e=await c.evaluate('window._exportExperiment');await writeFile(new URL('../evidence/browser-lab-export.json',import.meta.url),JSON.stringify(e,null,2)+'\n');const replay=replayExperiment(e);await writeFile(new URL('../evidence/browser-lab-replay.json',import.meta.url),JSON.stringify(replay,null,2)+'\n');assert.equal(replay.status,'EXACT');const tampered=structuredClone(e);tampered.checkpoint.state.tick++;assert.throws(()=>validateExperiment(tampered),/checksum/);return{status:replay.status,targetTick:replay.targetTick,fields:Object.keys(replay.branches.control).length};});
 await check('all three interventions are explicit and preserve baseline',async()=>{const p=makePlan(fixture,'metabolism-double',10,7);assert.equal(p.patch.baseMetabolism,fixture.provenance.config.baseMetabolism*2);assert.equal(p.patch.moveMetabolism,fixture.provenance.config.moveMetabolism*2);assert.deepEqual(makePlan(fixture,'toxin-zero',10).patch,{toxinEnergy:0});assert.throws(()=>makePlan(fixture,'food-half',-1));assert.throws(()=>compareOutcome(p,{tick:46,population:10},{tick:47,population:11}));return{metabolism:p.patch,toxin:0};});
 await check('experiment cancellation releases controls and source world',async()=>{await c.evaluate(`(()=>{document.getElementById('labTicks').value='10000';document.getElementById('labForm').requestSubmit();document.getElementById('labCancel').click();})()`);await waitFor(c,'!document.getElementById("labRun").disabled');const out=await c.evaluate('({message:document.getElementById("labStatus").textContent,tick:__GENESIS.sim.view.tick})');assert.match(out.message,/cancelled/i);assert.equal(out.tick,40);return out;});
 await check('invalid uploaded state reports error without hanging',async()=>{const out=await c.evaluate(`__GENESIS.load({state:{creatures:null}}).then(()=>false,e=>e.message)`);assert.match(out,/Invalid/);return out;});
 await c.evaluate(`__GENESIS.load(${JSON.stringify(fixture)})`);
 await check('readback returns actual nonempty WebGL pixels',async()=>{const out=await c.evaluate('(()=>{const r=__GENESIS.readback();return{width:r.width,height:r.height,nonzero:r.rgba.some(v=>v>0),backend:__GENESIS.renderer.constructor.name};})()');assert.ok(out.nonzero&&out.width>0);assert.equal(out.backend,'GLRenderer');return out;});
 await c.evaluate('document.getElementById("restartTour").click();__GENESIS.render()');
 const screen=await c.send('Page.captureScreenshot',{format:'png'});await writeFile(new URL('../evidence/browser-observatory.png',import.meta.url),Buffer.from(screen.data,'base64'));
 await check('reset restores the source seed and clears selected clade',async()=>{await c.evaluate('__GENESIS.reset()');const out=await c.evaluate('({tick:__GENESIS.sim.view.tick,seed:__GENESIS.sim.seed,clade:__GENESIS.state.highlightSpecies})');assert.equal(out.tick,0);assert.equal(out.seed,'browser-acceptance');assert.equal(out.clade,null);return out;});
 await check('Canvas query switches the real rendering backend',async()=>{await c.send('Page.navigate',{url:origin+'/?record=1&renderer=canvas&tour=0'});await waitFor(c,'!!window.__GENESIS');await c.evaluate('__GENESIS.ready');await c.evaluate(`__GENESIS.load(${JSON.stringify(fixture)})`);const out=await c.evaluate('({backend:__GENESIS.renderer.constructor.name,nonzero:__GENESIS.readback().rgba.some(v=>v>0)})');assert.equal(out.backend,'Renderer');assert.ok(out.nonzero);return out;});
 await check('scratch URL starts requested seed without loading curated state',async()=>{await c.send('Page.navigate',{url:origin+'/?scratch=1&seed=scratch-test&paused=1'});await waitFor(c,'document.getElementById("checkpointStatus")?.textContent.includes("Fresh seeded world")');const out=await c.evaluate('({tick:__GENESIS.sim.view.tick,seed:__GENESIS.sim.seed,choice:document.getElementById("checkpointSelect").value,paused:__GENESIS.state.stepsPerFrame===0})');assert.deepEqual(out,{tick:0,seed:'scratch-test',choice:'scratch',paused:true});return out;});
 await check('independent islands keep separate workers, seeds, and render configs',async()=>{await c.send('Page.navigate',{url:origin+'/?record=1&islands=2&seed=two-worlds'});await waitFor(c,'window.__GENESIS?.islands?.length===2 && __GENESIS.islands.every(i=>i.sim.config)');await c.evaluate('__GENESIS.render()');const out=await c.evaluate('({seeds:__GENESIS.islands.map(i=>i.sim.seed),workers:__GENESIS.islands[0].worker!==__GENESIS.islands[1].worker,heights:__GENESIS.islands.map(i=>i.canvas.clientHeight),configs:__GENESIS.islands.map(i=>i.renderer.config.foodRate)})');assert.deepEqual(out.seeds,['two-worlds-0','two-worlds-1']);assert.equal(out.workers,true);assert.ok(out.heights.every(h=>h>100));assert.deepEqual(out.configs,[36,36]);return out;});
 await check('Transferable fallback works without isolation headers',async()=>{const root=new URL('../',import.meta.url);fallbackServer=createServer(async(req,res)=>{try{const path=new URL(req.url,'http://localhost').pathname;const target=new URL('.'+(path==='/'?'/index.html':path),root);if(!target.href.startsWith(root.href)){res.writeHead(403).end();return;}const bytes=await readFile(fileURLToPath(target));res.writeHead(200,{'Content-Type':path.endsWith('.js')?'application/javascript':path.endsWith('.css')?'text/css':path.endsWith('.json')?'application/json':'text/html'}).end(bytes);}catch{res.writeHead(404).end('Not found');}});await new Promise(resolve=>fallbackServer.listen(0,'127.0.0.1',resolve));const port=fallbackServer.address().port;await c.send('Page.navigate',{url:`http://127.0.0.1:${port}/?record=1&tour=0`});await waitFor(c,'!!window.__GENESIS');await c.evaluate('__GENESIS.ready');await c.evaluate(`__GENESIS.load(${JSON.stringify(fixture)})`);const out=await c.evaluate(`(async()=>{await __GENESIS.step(2,{stats:false});return{isolated:crossOriginIsolated,sab:__GENESIS.sim._useSAB,badge:document.getElementById('transportBadge').textContent,tick:__GENESIS.sim.view.tick};})()`);assert.equal(out.isolated,false);assert.equal(out.sab,false);assert.equal(out.badge,'TRANSFER BUFFERS');assert.equal(out.tick,42);return out;});
 await check('no uncaught browser exceptions',()=>{assert.deepEqual(errors,[]);return errors;});
} finally {if(browser)await browser.close();if(fallbackServer)await new Promise(resolve=>fallbackServer.close(resolve));await writeFile(new URL('../evidence/browser-tests.json',import.meta.url),JSON.stringify({checks:results,uncaught:errors},null,2)+'\n');}
if(results.some(r=>!r.ok))process.exitCode=1;
